In [3]:
!!! Bài 1. Tạo Tensor cơ bản
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [4]:
!!! Bài 2. Tạo các Tensor thường dùng
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.7046, 0.4451, 0.7387, 0.6200],
        [0.8801, 0.7022, 0.8282, 0.0834],
        [0.1604, 0.5478, 0.0990, 0.0456]])
tensor([[-0.3427,  2.7946,  0.9824,  0.2853],
        [ 0.6584, -0.4408, -0.2710, -0.3714],
        [-1.6783, -1.1921, -0.0976,  0.5026]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [6]:
!!! Bài 3. Kiểm tra thông tin Tensor
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3


In [7]:
!!! Bài 4. Slicing và Indexing
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.6088, -1.0457, -2.0743, -0.9951,  0.8633],
         [ 0.7892,  1.9753, -0.4187, -1.0091, -1.3136],
         [-1.0522,  0.2527, -0.6074, -0.5534, -0.3080],
         [-0.2093, -0.6564,  0.5374,  0.4823,  0.5847]],

        [[ 0.8953,  0.3698,  0.1580, -0.7535, -0.0858],
         [ 0.4013, -0.0051, -0.0505, -1.4368,  0.1331],
         [-0.1568,  1.3409, -1.7630,  0.7480,  0.9010],
         [ 0.6316, -0.0813,  0.2541,  0.2087,  0.8628]],

        [[-1.6854, -0.8394,  1.5019,  0.1502,  0.6497],
         [-0.1871, -0.4669, -0.8509,  0.1192, -1.0362],
         [-0.2630,  0.7135, -0.4128,  1.8885,  0.3539],
         [-0.2244, -0.4608,  0.5155, -0.6976,  1.4389]]])

Tensor a[1]:
tensor([[ 0.8953,  0.3698,  0.1580, -0.7535, -0.0858],
        [ 0.4013, -0.0051, -0.0505, -1.4368,  0.1331],
        [-0.1568,  1.3409, -1.7630,  0.7480,  0.9010],
        [ 0.6316, -0.0813,  0.2541,  0.2087,  0.8628]])

Tensor a[1:, 2:4]:
tensor([[[-0.1568,  1.3409, -1.7630,  0.7480,  0.9