In [3]:
!!! Bài 1. Tạo Tensor cơ bản
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [16]:
!!! Bài 2. Tạo các Tensor thường dùng
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4260, 0.1809, 0.8309, 0.1198],
        [0.9747, 0.4608, 0.9362, 0.8916],
        [0.2736, 0.6318, 0.6279, 0.4387]])
tensor([[-0.7299, -0.5562, -1.6750, -0.0134],
        [-1.0170,  1.0595, -0.3210,  0.3375],
        [-0.3081,  1.0035,  1.1547,  0.1272]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [18]:
!!! Bài 2.Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10
import torch

f1 = torch.full((5, 5), 10)
print(f1)

f2 = torch.ones(5, 5) * 10
print(f2)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


In [6]:
!!! Bài 3. Kiểm tra thông tin Tensor
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)


Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3


In [22]:
!!! Bài 4. Slicing và Indexing
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.4701, -0.2229, -0.0644, -0.2669, -0.2245],
         [-1.8870,  0.8255,  1.6343,  0.1078, -0.0951],
         [-0.7019, -0.4285,  0.9984, -0.2206, -0.0102],
         [-0.7930, -0.4762,  0.5807,  0.7290, -0.2337]],

        [[ 0.2137, -1.0609,  0.1783, -0.8450,  0.2112],
         [-0.1444,  0.8101, -1.0167,  0.1260, -0.7351],
         [-0.4841, -0.3165, -0.6481, -0.8096, -1.2524],
         [ 1.4597,  0.3033, -2.5350,  1.2042,  1.1922]],

        [[-1.1354, -0.3198,  1.1334, -0.4788, -0.3232],
         [-0.1254, -0.7711,  1.3164, -0.1352, -1.1331],
         [-0.7220, -0.1225, -0.8472, -1.6105,  0.4252],
         [ 0.8974, -0.9979,  0.5151,  0.2705, -1.0178]]])

Tensor a[1]:
tensor([[ 0.2137, -1.0609,  0.1783, -0.8450,  0.2112],
        [-0.1444,  0.8101, -1.0167,  0.1260, -0.7351],
        [-0.4841, -0.3165, -0.6481, -0.8096, -1.2524],
        [ 1.4597,  0.3033, -2.5350,  1.2042,  1.1922]])

Tensor a[1:, 2:4]:
tensor([[[-0.4841, -0.3165, -0.6481, -0.8096, -1.2

In [20]:
!!! Bài 4. Thử lấy hai phần tử cuối cùng trên chiều thứ ba.
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nHai phần tử cuối cùng trên chiều thứ ba (a[:, :, -2:]):")
print(a[:, :, -2:])

Original tensor:
tensor([[[ 0.6808, -0.6660,  2.1505,  0.6527,  2.1320],
         [-1.2873,  0.3643,  0.1490,  0.6521, -0.1316],
         [-0.4249, -0.5406,  1.4310, -0.7054, -0.7721],
         [-1.0856, -0.2535, -0.0299, -1.6503, -0.2395]],

        [[-0.3787, -0.3089, -0.3204, -0.2930,  0.1433],
         [-1.6858,  0.9014, -0.6293, -0.8887, -0.4007],
         [-1.4534, -0.2037, -0.0822,  1.2983,  0.0545],
         [-0.2382,  0.7857,  0.3190,  0.1953,  1.9012]],

        [[-0.2702,  1.4251, -0.8374, -1.4388,  0.0389],
         [ 2.1855,  0.4371,  0.3018, -0.6046,  0.8608],
         [-0.2451, -0.1257,  0.1859, -1.1664, -0.3982],
         [-0.4787,  1.3816, -1.1139,  0.4961,  0.7608]]])

Tensor a[1]:
tensor([[-0.3787, -0.3089, -0.3204, -0.2930,  0.1433],
        [-1.6858,  0.9014, -0.6293, -0.8887, -0.4007],
        [-1.4534, -0.2037, -0.0822,  1.2983,  0.0545],
        [-0.2382,  0.7857,  0.3190,  0.1953,  1.9012]])

Hai phần tử cuối cùng trên chiều thứ ba (a[:, :, -2:]):
tensor([[[ 0.

In [21]:
!!!Bài 5. Reshape và Flatten
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.4825,  0.8858, -0.8143, -0.1031],
        [-0.5870,  0.3852, -0.8097,  2.1880],
        [-1.8061,  0.9506,  0.2344, -1.0943]])

Flatten:
tensor([ 0.4825,  0.8858, -0.8143, -0.1031, -0.5870,  0.3852, -0.8097,  2.1880,
        -1.8061,  0.9506,  0.2344, -1.0943])

Reshape to 3 x 2 x 2:
tensor([[[ 0.4825,  0.8858],
         [-0.8143, -0.1031]],

        [[-0.5870,  0.3852],
         [-0.8097,  2.1880]],

        [[-1.8061,  0.9506],
         [ 0.2344, -1.0943]]])


In [23]:
!!!Bài 5. Thử reshape Tensor thành kích thước 2 × 6.
import torch

a = torch.randn(3, 4)
print("Số phần tử của Tensor ban đầu:", a.numel())

# Reshape thành kích thước 2 x 6
a_2x6 = a.reshape(2, 6)

print("\nTensor sau khi reshape thành 2x6:")
print(a_2x6)
print("Số phần tử sau khi reshape:", a_2x6.numel())

Số phần tử của Tensor ban đầu: 12

Tensor sau khi reshape thành 2x6:
tensor([[ 1.0164, -1.4997, -0.3680, -0.3620, -2.3102, -0.0198],
        [-0.9473,  0.5111, -1.6153, -1.1795, -0.9399,  1.7357]])
Số phần tử sau khi reshape: 12


In [4]:
!!! Bài 6. Phép toán và nhân ma trận
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.4534, -0.8407,  1.5311],
        [-1.4448,  0.5993, -1.6968]])
b:
tensor([[ 0.1193,  1.2922, -0.8397],
        [ 0.5532,  0.6560,  0.3051]])

a + b:
tensor([[ 1.5727,  0.4514,  0.6914],
        [-0.8916,  1.2554, -1.3916]])

a / b:
tensor([[12.1855, -0.6506, -1.8233],
        [-2.6116,  0.9136, -5.5610]])

a^2:
tensor([[2.1123, 0.7068, 2.3441],
        [2.0875, 0.3592, 2.8790]])

Matrix multiplication:
tensor([[-2.1986,  0.7197],
        [ 2.0269, -0.9239]])


In [5]:
!!!Bài 7. Các hàm thống kê trên Tensor
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.4060,  1.1897,  0.3274,  0.5985],
        [ 0.7514,  0.0082, -0.1632, -0.6828],
        [-2.3681, -1.1812, -1.9295,  1.2428]])

Mean:
tensor([-0.6742,  0.0056, -0.5885,  0.3862])

Standard deviation:
tensor([1.5770, 1.1855, 1.1870, 0.9802])

Cumulative sum:
tensor([[-0.4060,  1.1897,  0.3274,  0.5985],
        [ 0.3454,  1.1979,  0.1641, -0.0843],
        [-2.0227,  0.0167, -1.7654,  1.1586]])


In [6]:
!!! Bài 8. Autograd cơ bản
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [25]:
!!! Bài 8. Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.
import torch
x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


In [29]:
!!! Bài 9. Gradient Descent tìm hệ số đa thức
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
    X * X,
    X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.6847],
        [1.4804],
        [0.4620]], requires_grad=True)
Learned coefficients:
tensor([[1.0028],
        [2.0104],
        [2.9160]], requires_grad=True)


In [28]:
!!! Bài 10. Giải hệ phương trình bằng Autograd
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.5329, requires_grad=True)
B = tensor(4.4671, requires_grad=True)
C = tensor(3.4671, requires_grad=True)
D = tensor(2.4671, requires_grad=True)


In [27]:
!!! Bài 11. Viết chương trình PyTorch để thực hiện các yêu cầu sau:
import torch
import numpy as np

!!! a.) Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
# Tạo tensor X có 24 phần tử (từ 0 đến 23)
X = torch.arange(24)
print("X ban đầu (24 phần tử):", X)

# Reshape thành 4x6, 2x12 và 2x3x4
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("\nX reshape 4x6:\n", X_4x6)
print("\nX reshape 2x12:\n", X_2x12)
print("\nX reshape 2x3x4:\n", X_2x3x4)


!!! b.) Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
# Tạo 2 tensor A và B kích thước 3x4 ngẫu nhiên
A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("Tensor A:\n", A)
print("Tensor B:\n", B)

# Các phép toán cơ bản (Element-wise)
print("\nA + B:\n", A + B)
print("A * B:\n", A * B)
print("A / B:\n", A / B)

# Tính trung bình và độ lệch chuẩn theo cột (dim=0)
# Giả sử yêu cầu tính trên Tensor A (bạn có thể áp dụng tương tự cho B)
mean_A_col = A.mean(dim=0)
std_A_col = A.std(dim=0)
print("\nTrung bình của A theo cột:\n", mean_A_col)
print("Độ lệch chuẩn của A theo cột:\n", std_A_col)


!!! c.) Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
# Khởi tạo x = 2, requires_grad=True để theo dõi đạo hàm
x = torch.tensor(2.0, requires_grad=True)

# Khai báo hàm số y = 2x^2 + 5x + 3
y = 2 * x**2 + 5 * x + 3

# Kích hoạt tính toán lan truyền ngược để tìm đạo hàm
y.backward()

# In kết quả từ Autograd
print(f"Giá trị dy/dx tại x=2 (tính bằng Autograd): {x.grad.item()}")

# Kiểm tra bằng phép tính thủ công
# y  = 2x^2 + 5x + 3
# y' = 4x + 5
# Tại x = 2 => y' = 4(2) + 5 = 13
thu_cong = 4 * 2.0 + 5
print(f"Giá trị dy/dx tại x=2 (tính thủ công): {thu_cong}")


!!! d.) Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.
# 1. Tạo dữ liệu giả lập (Ground Truth)
N = 100
X_data = np.random.randn(N, 1) * 5
# Đa thức y = 2x^2 - 3x + 5
Y_data = 2 * (X_data**2) - 3 * X_data + 5

# 2. Xây dựng ma trận đặc trưng XX bao gồm [x^2, x, 1]
XX = np.hstack([
    X_data**2, 
    X_data, 
    np.ones_like(X_data)
])

# Khởi tạo trọng số w ngẫu nhiên (kích thước 3x1)
w = torch.randn(3, 1, requires_grad=True)

# Chuyển đổi dữ liệu numpy sang torch tensor
x_tensor = torch.tensor(XX, dtype=torch.float32)
y_tensor = torch.tensor(Y_data, dtype=torch.float32)

# Khởi tạo thuật toán tối ưu (sử dụng Adam hoặc NAdam với learning rate 0.05)
optimizer = torch.optim.NAdam([w], lr=0.05)

# Huấn luyện mô hình
epochs = 2000
for epoch in range(epochs):
    # Reset gradient
    optimizer.zero_grad()
    
    # Dự đoán
    y_pred = x_tensor @ w
    
    # Tính hàm mất mát (Mean Squared Error)
    loss = torch.mean(torch.square(y_tensor - y_pred))
    
    # Lan truyền ngược và cập nhật trọng số
    loss.backward()
    optimizer.step()

# In kết quả
print("Các hệ số thực tế của đa thức (a, b, c): [2.0, -3.0, 5.0]")
print("Các hệ số tìm được sau khi huấn luyện:")
print(w.detach().numpy().flatten())

X ban đầu (24 phần tử): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

X reshape 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

X reshape 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

X reshape 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Tensor A:
 tensor([[ 0.3771, -0.4833,  1.7217,  1.0135],
        [-0.4328,  0.3038,  0.2269, -2.3018],
        [-0.9217,  1.4738, -0.2672,  0.7736]])
Tensor B:
 tensor([[ 1.7828, -0.1141, -0.3263,  1.0487],
        [ 0.3197, -0.6758,  0.7960,  1.2721],
        [ 0.5719, -0.0536, -1.3032, -0.8642]])

A + B:
 tensor([[ 2.1599, -0.5974,  1.3954,  2.0622],
        [-0.1131, -0.3719,  1.0228